name: Tweet Scheduler (duygu)

on:
  schedule:
    - cron: '*/5 * * * *'   # Her 5 dakikada bir (UTC)
  workflow_dispatch:        # Elle tetikleme

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run dispatcher (duygu)
        run: |
          echo "$X_REFRESH_TOKEN" > .x_refresh_token
          python dispatcher_duygu.py
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          X_MODEL: ${{ secrets.X_MODEL }}
          X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
          X_CLIENT_SECRET: ${{ secrets.X_CLIENT_SECRET }}
          X_REDIRECT_URI: ${{ secrets.X_REDIRECT_URI }}
          X_SCOPES: ${{ secrets.X_SCOPES }}
          X_REFRESH_TOKEN: ${{ secrets.X_REFRESH_TOKEN }}
